// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwtxebgyiknysfmpeejy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3dHhlYmd5aWtueXNmbXBlZWp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI0NzQ0MDMsImV4cCI6MjA0ODA1MDQwM30.vPOJNrbsQ2MSovY64afTjxHe-Lc1VCLslop4yvOf9A0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);